name: Manual Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      heroku_app_name:
        description: "Enter your Heroku App Name"
        required: true
      heroku_email:
        description: "Enter your Heroku Account Email"
        required: true
      heroku_api_key:
        description: "Enter your Heroku API Key"
        required: true
      heroku_team_name:
        description: "Enter your Heroku Team Name (optional)"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # কোড চেকআউট
    - name: Checkout repository
      uses: actions/checkout@v3

    # Heroku CLI ইনস্টল করা
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    # Heroku CLI দিয়ে লগইন
    - name: Login to Heroku Container Registry
      run: |
        echo "${{ github.event.inputs.heroku_api_key }}" | docker login --username=${{ github.event.inputs.heroku_email }} --password-stdin registry.heroku.com

    # Docker ইমেজ বিল্ড এবং পুশ
    - name: Build and Push Docker Image
      run: |
        docker build -t registry.heroku.com/${{ github.event.inputs.heroku_app_name }}/web .
        docker push registry.heroku.com/${{ github.event.inputs.heroku_app_name }}/web

    # Heroku ইমেজ রিলিজ
    - name: Release Docker Image
      run: |
        if [ -n "${{ github.event.inputs.heroku_team_name }}" ]; then
          heroku container:release web --app ${{ github.event.inputs.heroku_app_name }} --team ${{ github.event.inputs.heroku_team_name }}
        else
          heroku container:release web --app ${{ github.event.inputs.heroku_app_name }}
        fi

      env:
        HEROKU_API_KEY: ${{ github.event.inputs.heroku_api_key }}
